### PR TITLE
Install and compile kiwix-desktop on xenial for appimage.

### PR DESCRIPTION
**Pull request by mgautierfr**

### CODE REVIEW

**Comment by mgautierfr** [comment]
This PR install qt using the official installer on xenial. So we can compile kiwix-desktop and create the appimage on xenial.

The appimage is created and run on xenial. But it fails to run on Ubuntu 19.04.
The error message is :
```
MESA-LOADER: failed to open swrast (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri)
libGL error: failed to load driver: swrast
"/home/mgautier/.local/share/kiwix"
3
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
QGLXContext: Failed to create dummy context
add widget
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Abandon (core dumped)
```

Maybe @probonopd has a idea of what is wrong.
(Sample test "wrong" appimage is available at http://public.kymeria.fr/KIWIX/kiwix-desktop_x86_64_2019-09-26.appimage)

**Comment by probonopd** [comment]
@mgautierfr I do not get this error on Ubuntu 18.04.2 LTS.

Please see if the issue disappears when you run

    ./kiwix-desktop_x86_64_2019-09-26.appimage --appimage-extract
    rm -rf squashfs-root/usr/lib/libstdc++.*
    ./squashfs-root/AppRun

If it works using those commands, then the following options might solve this:

* If possible, compile on the oldest still-supported Ubuntu LTS release (currently xenial) without adding compilers (e.g., through ppas) that draw in newer versions of `libstdc++.so.6` than what comes with the distribution. Do _not_ bundle a private copy of `libstdc++.so.6`  in the AppImage. (`linuxdeployqt` should not have done that anyway.)
* If this is not possible, then maybe using https://github.com/darealshinji/AppImageKit-checkrt/ can help. It will search for `usr/optional/libstdc++/libstdc++.so.6` and `usr/optional/libgcc_s/libgcc_s.so.1` inside the AppImage or AppDir. If found it will compare their internal versions with the ones found on the system and prepend their paths to `LD_LIBRARY_PATH` _if necessary_.

More information:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6

**Comment by kelson42** [comment]
@mgautierfr I guess we can close this PR and delete the branch?

**Comment by probonopd** [comment]
Unless someone still needs xenial, yes.

The currently oldest still-supported Ubuntu release is bionic (until [April 2023](https://lists.ubuntu.com/archives/ubuntu-announce/2018-April/000231.html)), so I think it would be reasonable to target that nowadays.

**Pull request closed without merging**
