### PR TITLE
Update Readme.MD, correct spelling error

### PR DESCRIPTION
**Pull request by jhbiggs**
"Prerequisite"

### CODE REVIEW

**Comment by kelson42** [comment]
@jhbiggs Could you please rebase on develop branch? We usually never merge directly to master.

**Comment by jhbiggs** [comment]
Sorry, where is the develop branch?

**Comment by jhbiggs** [comment]
Hi @kelson42 I sought the develop branch but haven't found it on this repository.  I must be missing something.  I would like to update the readme.md file in a couple of other places, but will wait until I hear from you.  I want to make sure to do a pull request in the right branch.

**Comment by kelson42** [comment]
@jhbiggs Sorry for misleading you, this develop branch exists only on kiwiy-android repo.

**Pull request merged**
