### PR TITLE
No shell

### PR DESCRIPTION
**Pull request by mgautierfr**

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Can we delete this PR and the branch?

**Comment by mgautierfr** [comment]
No.
This is part of the job to be able to correctly run kiwix-build on windows.
I've stopped to work on this and compile kiwix-desktop using plain scripts. But at a time we will have to do the things correctly. And we will need this code.

**Comment by kelson42** [comment]
@mgautierfr A ticket should be open about that (explaining the problem) and linked to this PR. Then I propose to close the PR and remove the branch using github interface. That way will easily be able to recover the code at the time needed.

**Comment by mgautierfr** [comment]
We may close the PR, but why delete the branch ?

**Comment by kelson42** [comment]
@mgautierfr We can do so, but i'm not really in favour of keeping branches for years.

**Pull request closed without merging**
