### PR TITLE
Enable inmemory backend in xapian

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Required for kiwix/kiwix-lib#460

### CODE REVIEW

**Comment by kelson42** [comment]
I’m not 100% sure, but we might need to bumpup the version number to secure new CI deps are computed?!

**Comment by veloman-yunkan** [comment]
> I’m not 100% sure, but we might need to bumpup the version number to secure new CI deps are computed?!

The comment makes sense, however the problem is that the version of `xapian-core` dependency hasn't changed. Is bumping `base_deps_meta_version` enough?

https://github.com/kiwix/kiwix-build/blob/b635daae68ba88304af8a710531989d71d7cc910/kiwixbuild/versions.py#L40-L42

**Comment by kelson42** [comment]
@veloman-yunkan I believe so... but we need to update to latest Xapian maintenance release anyway as well...

**Comment by kelson42** [comment]
I will approve this PR and create a subsequent one to upgrade to 1.4.18.

**Comment by mgautierfr** [comment]
>  Is bumping base_deps_meta_version enough?

Yes it is. (would have been) (and it would have been necessary without #478)

**Pull request merged**
