### PR TITLE
Add macOS_arm64_mixed platform.

### LINKED ISSUE #511: Fix macOS_* targets
PR #499 introduces new `macOS_x86_64` and `macOS_arm64` targets used primarily to build libkiwix for macOS and iOS Apps.

Binary projects such as zim-tools and kiwix-tools don't work with those targets but could with some tweaks.

Details on [PR#499](https://github.com/kiwix/kiwix-build/pull/499#issuecomment-952903125)

### LINKED ISSUE #570: Member kelson42 commented 9 hours ago •  edited  And also for macOS Apple M1/M2, but depends on github/roadmap#528
Publish libzim for macOS on Apple M1/M2, but depends on https://github.com/github/roadmap/issues/528

### PR DESCRIPTION
**Pull request by mgautierfr**
Fixes #570 
Fixes #511

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr I have put two ticket numbers fixed by this PR. I hope this is correct because I'm unsure. Please verify with the whole list of open tickets to check if I don't have missed other one.

In general, please put the tickets concerned by your PR early, so everybody understand what is going one and act accordingly.

**Comment by kelson42** [comment]
@mgautierfr What is the status here?

**Comment by mgautierfr** [comment]
I **think** it is ok.
But this is not tested (at leas by me)

**Comment by mgautierfr** [comment]
Output is here : https://tmp.kiwix.org/ci/macos_arm64/

And it (libzim archive) looks good.

**Comment by kelson42** [comment]
> Output is here : https://tmp.kiwix.org/ci/macos_arm64/
> 
> And it (libzim archive) looks good.

@rgaudin @automactic Does that look good to you? Is that in the correct form or do you need another kind of packaging?

**Comment by rgaudin** [comment]
It does ; I am testing it already before accepting. AFAIK, @automactic doesn't care for libzim.

**Comment by mgautierfr** [comment]
Let's merge it then.

**Pull request merged**
