### PR TITLE
Build zim-tools and kiwix-tools on macos-arm64

### LINKED ISSUE #592: Publish kiwix-tools on macOS

### LINKED ISSUE #593: zim-tools should be published on macOS ARM

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #593
Fix #592

### CODE REVIEW

**Comment by mgautierfr** [comment]
@rgaudin Can you try https://tmp.kiwix.org/ci/dev_preview/tools_on_macos_m1/kiwix-tools_macos-arm64-2023-11-07.tar.gz and https://tmp.kiwix.org/ci/dev_preview/tools_on_macos_m1/zim-tools_macos-arm64-2023-11-07.tar.gz ?

This PR removes the `-fembed-bitcode` option. I don't know the implication but it is also removed in #638 so I suppose we are ok.

**Comment by rgaudin** [comment]
Both work fine (tested kiwix-serve and zimcheck) 👍 

Indeed, as explained, we want to remove bitcode from now

**Comment by kelson42** [comment]
@mgautierfr Is that ready to review by @rgaudin?

**Comment by mgautierfr** [comment]
> @mgautierfr Is that ready to review by @rgaudin?

It is, but the PR is really simple, most of the job has been made in #638.
I'm merging directly.

**Pull request merged**
