### PR TITLE
Catalyst abi

### PR DESCRIPTION
**Pull request by automactic**
Add UIKit for macOS (aka project catalyst) as a build target. 

`kiwix-build --target-platform iOS_Mac_ABI kiwix-lib`

@mgautierfr could you help me add a build in CI?

### CODE REVIEW

**Comment by kelson42** [comment]
@automactic Thank you for the PR but there is no helpful description nor commit messages. Would you be able please to rewrite commit msgs so they describe what the commit does, maybe you can squash all commits in one?... And add a PR des ription, considering that there is not ticket open linked?

**Comment by automactic** [comment]
@kelson42 I haven't finished yet

**Comment by kelson42** [comment]
Please put your PR in draft in that case, this would be then clearer.

**Comment by mgautierfr** [comment]
The macos run are launch from here : https://github.com/kiwix/kiwix-build/blob/master/.github/workflows/ci.yml#L107-L158

Simply add `iOS_Mac_ABI` to the targets should work.

**Comment by kelson42** [comment]
@automactic Any update of this PR?

**Comment by automactic** [comment]
@mgautierfr Hey I finally got back to this and added CI, could you please take a look?

**Pull request merged**
