### PR TITLE
New version of xapian 1.4.22

### LINKED ISSUE #599: Update xapian version
I'm sorry but it's becoming a pain to test. I can't compile on macOS and neither can I on a `debian:bullseye` container

```
[4/102] ccache c++ -Itest/library.p -Iinclude -I../../SOURCE/libkiwix/include -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -DCURL_STATICLIB -pthread -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest -isystemsubprojects/googletest-release-1.8.1/googletest -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/include -MD -MQ test/library.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest_main.cc.o -MF test/library.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest_main.cc.o.d -o test/library.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest_main.cc.o -c ../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/src/gtest_main.cc
[5/102] ccache c++ -Itest/regex.p -Iinclude -I../../SOURCE/libkiwix/include -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -DCURL_STATICLIB -pthread -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest -isystemsubprojects/googletest-release-1.8.1/googletest -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/include -MD -MQ test/regex.p/regex.cpp.o -MF test/regex.p/regex.cpp.o.d -o test/regex.p/regex.cpp.o -c ../../SOURCE/libkiwix/test/regex.cpp
[6/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/meson-generated_.._.._static_libkiwix-resources.cpp.o -MF src/libkiwix.a.p/meson-generated_.._.._static_libkiwix-resources.cpp.o.d -o src/libkiwix.a.p/meson-generated_.._.._static_libkiwix-resources.cpp.o -c static/libkiwix-resources.cpp
[7/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/meson-generated_.._.._static_libkiwix-i18n-resources.cpp.o -MF src/libkiwix.a.p/meson-generated_.._.._static_libkiwix-i18n-resources.cpp.o.d -o src/libkiwix.a.p/meson-generated_.._.._static_libkiwix-i18n-resources.cpp.o -c static/libkiwix-i18n-resources.cpp
[8/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/bookmark.cpp.o -MF src/libkiwix.a.p/bookmark.cpp.o.d -o src/libkiwix.a.p/bookmark.cpp.o -c ../../SOURCE/libkiwix/src/bookmark.cpp
[9/102] ccache c++ -Itest/library.p -Iinclude -I../../SOURCE/libkiwix/include -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -DCURL_STATICLIB -pthread -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest -isystemsubprojects/googletest-release-1.8.1/googletest -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/include -MD -MQ test/library.p/library.cpp.o -MF test/library.p/library.cpp.o.d -o test/library.p/library.cpp.o -c ../../SOURCE/libkiwix/test/library.cpp
[10/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/book.cpp.o -MF src/libkiwix.a.p/book.cpp.o.d -o src/libkiwix.a.p/book.cpp.o -c ../../SOURCE/libkiwix/src/book.cpp
[11/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/manager.cpp.o -MF src/libkiwix.a.p/manager.cpp.o.d -o src/libkiwix.a.p/manager.cpp.o -c ../../SOURCE/libkiwix/src/manager.cpp
[12/102] ccache c++ -Itest/library.p -Iinclude -I../../SOURCE/libkiwix/include -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -DCURL_STATICLIB -pthread -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest -isystemsubprojects/googletest-release-1.8.1/googletest -isystem../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/include -MD -MQ test/library.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.o -MF test/library.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.o.d -o test/library.p/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.o -c ../../SOURCE/libkiwix/subprojects/googletest-release-1.8.1/googletest/src/gtest-all.cc
[13/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/libxml_dumper.cpp.o -MF src/libkiwix.a.p/libxml_dumper.cpp.o.d -o src/libkiwix.a.p/libxml_dumper.cpp.o -c ../../SOURCE/libkiwix/src/libxml_dumper.cpp
[14/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/opds_dumper.cpp.o -MF src/libkiwix.a.p/opds_dumper.cpp.o.d -o src/libkiwix.a.p/opds_dumper.cpp.o -c ../../SOURCE/libkiwix/src/opds_dumper.cpp
[15/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/downloader.cpp.o -MF src/libkiwix.a.p/downloader.cpp.o.d -o src/libkiwix.a.p/downloader.cpp.o -c ../../SOURCE/libkiwix/src/downloader.cpp
[16/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/library_dumper.cpp.o -MF src/libkiwix.a.p/library_dumper.cpp.o.d -o src/libkiwix.a.p/library_dumper.cpp.o -c ../../SOURCE/libkiwix/src/library_dumper.cpp
[17/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/html_dumper.cpp.o -MF src/libkiwix.a.p/html_dumper.cpp.o.d -o src/libkiwix.a.p/html_dumper.cpp.o -c ../../SOURCE/libkiwix/src/html_dumper.cpp
[18/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/subprocess.cpp.o -MF src/libkiwix.a.p/subprocess.cpp.o.d -o src/libkiwix.a.p/subprocess.cpp.o -c ../../SOURCE/libkiwix/src/subprocess.cpp
[19/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/server.cpp.o -MF src/libkiwix.a.p/server.cpp.o.d -o src/libkiwix.a.p/server.cpp.o -c ../../SOURCE/libkiwix/src/server.cpp
[20/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/tools_base64.cpp.o -MF src/libkiwix.a.p/tools_base64.cpp.o.d -o src/libkiwix.a.p/tools_base64.cpp.o -c ../../SOURCE/libkiwix/src/tools/base64.cpp
[21/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/aria2.cpp.o -MF src/libkiwix.a.p/aria2.cpp.o.d -o src/libkiwix.a.p/aria2.cpp.o -c ../../SOURCE/libkiwix/src/aria2.cpp
[22/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/library.cpp.o -MF src/libkiwix.a.p/library.cpp.o.d -o src/libkiwix.a.p/library.cpp.o -c ../../SOURCE/libkiwix/src/library.cpp
FAILED: src/libkiwix.a.p/library.cpp.o
ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/library.cpp.o -MF src/libkiwix.a.p/library.cpp.o.d -o src/libkiwix.a.p/library.cpp.o -c ../../SOURCE/libkiwix/src/library.cpp
In file included from /kiwix-build/./BUILD_native_static/INSTALL/include/xapian.h:80,
                 from ../../SOURCE/libkiwix/src/library.cpp:37:
/kiwix-build/./BUILD_native_static/INSTALL/include/xapian/queryparser.h: In member function ‘void Xapian::QueryParser::add_valuerangeprocessor(Xapian::ValueRangeProcessor*)’:
/kiwix-build/./BUILD_native_static/INSTALL/include/xapian/queryparser.h:1266:26: error: ‘void Xapian::QueryParser::add_valuerangeprocessor(Xapian::ValueRangeProcessor*)’ is deprecated [-Werror=deprecated-declarations]
 1266 |  add_rangeprocessor((new ShimRangeProcessor(vrproc))->release());
      |                          ^~~~~~~~~~~~~~~~~~
In file included from /kiwix-build/./BUILD_native_static/INSTALL/include/xapian/types.h:28,
                 from /kiwix-build/./BUILD_native_static/INSTALL/include/xapian.h:47,
                 from ../../SOURCE/libkiwix/src/library.cpp:37:
/kiwix-build/./BUILD_native_static/INSTALL/include/xapian/queryparser.h:1246:28: note: declared here
 1246 |     XAPIAN_DEPRECATED(void add_valuerangeprocessor(Xapian::ValueRangeProcessor * vrproc)) {
      |                            ^~~~~~~~~~~~~~~~~~~~~~~
/kiwix-build/./BUILD_native_static/INSTALL/include/xapian/deprecated.h:50:32: note: in definition of macro ‘XAPIAN_DEPRECATED’
   50 | #  define XAPIAN_DEPRECATED(D) D __attribute__((__deprecated__))
      |                                ^
cc1plus: all warnings being treated as errors
[23/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/tools_regexTools.cpp.o -MF src/libkiwix.a.p/tools_regexTools.cpp.o.d -o src/libkiwix.a.p/tools_regexTools.cpp.o -c ../../SOURCE/libkiwix/src/tools/regexTools.cpp
[24/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/tools_pathTools.cpp.o -MF src/libkiwix.a.p/tools_pathTools.cpp.o.d -o src/libkiwix.a.p/tools_pathTools.cpp.o -c ../../SOURCE/libkiwix/src/tools/pathTools.cpp
[25/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/tools_stringTools.cpp.o -MF src/libkiwix.a.p/tools_stringTools.cpp.o.d -o src/libkiwix.a.p/tools_stringTools.cpp.o -c ../../SOURCE/libkiwix/src/tools/stringTools.cpp
[26/102] ccache c++ -Isrc/libkiwix.a.p -Isrc -I../../SOURCE/libkiwix/src -Iinclude -I../../SOURCE/libkiwix/include -Istatic -I/kiwix-build/./BUILD_native_static/INSTALL/include -I/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -std=c++11 -O0 -g -fPIC -DCURL_STATICLIB -pthread -MD -MQ src/libkiwix.a.p/search_renderer.cpp.o -MF src/libkiwix.a.p/search_renderer.cpp.o.d -o src/libkiwix.a.p/search_renderer.cpp.o -c ../../SOURCE/libkiwix/src/search_renderer.cpp
ninja: build stopped: subcommand failed.
```

_Originally posted by @rgaudin in https://github.com/kiwix/libkiwix/issues/940#issuecomment-1518730634_

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #599

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Don't forget to open and link ticket upstream. Seems necessary here.

**Comment by kelson42** [comment]
@mgautierfr Can we merge this?

**Comment by mgautierfr** [comment]
Associated ticket is https://trac.xapian.org/ticket/821

**Comment by mgautierfr** [comment]
> Can we merge this?

Yes !

**Pull request merged**
