### PR TITLE
Move back to the old toolchain for aarch64

### LINKED ISSUE #634: aarch64 bionic should not require GLIBCXX 3.4.26 and 3.4.29
See the downstream ticket https://github.com/openzim/python-libzim/issues/170

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #634

### CODE REVIEW

**Review by rgaudin — APPROVED** [review]
LGTM

**Comment by mgautierfr** [comment]
Same number of binaries, same names.

Only aarch64 binary is build with a older toolchain and so avoid too recent glibcxx symbols.

**Comment by rgaudin** [comment]
What's the status of this? I was under the impression we'd have a new build of 8.2.1 but this has not been merged yet

**Comment by mgautierfr** [comment]
Should be merged.
Done now.

**Pull request merged**
