### PR TITLE
Multi arch

### LINKED ISSUE #172: Be able to handle different build environment in the same time.
For now, kiwix-build internally setup a build environment (with associated toolchains, option, ...) and a series of projects/dependencies in the right order. It then build each project using the created build environment.

Handling only one build environment means that we cannot build "in the same time" different versions
of a project. However it is needed by #113, #108 and #77 and to avoid "external" script like in #147.

- A target (a project/dependency) should be associated to a platform.
- Be able to have "meta platform" regrouping different platforms like android regrouping all android variants. (Especially to allow command line options)
- A target may have to be build several times with the real platform (dependencies, libraries, apk,...) or once in the meta-platform (fat library, universal apks, ...)

### PR DESCRIPTION
**Pull request by mgautierfr**
fix #172 

@mhutti1 @automactic, with this PR, `kiwix-build` will be able to generate multi-arch apk and kiwix-lib fatlibs.

I've updated the README but as reminder, the commands to run are :
```
$ kiwix-build kiwix-android  # Or :
$ kiwix-build --target-platform iOS_multi kiwix-lib
```

Can you test on your side an confirm that apks and fatlib are correctly working ?

### CODE REVIEW

**Comment by mhutti1** [comment]
```[INSTALL PACKAGES]
SKIP
[PREPARE]
prepare sources Gradle :
  download Gradle : SKIP
  extract Gradle : SKIP
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c : SKIP
  svnupdate icu4c : OK
  patch icu4c : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : SKIP
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
prepare sources kiwix-android :
  gitclone kiwix-android : SKIP
  gitupdate kiwix-android : OK
[BUILD]
build Gradle :
  install Gradle : OK
build pugixml :
  configure pugixml : SKIP
  compile pugixml : OK
  test pugixml : OK
  install pugixml : OK
build lzma :
  configure lzma : SKIP
  compile lzma : SKIP
  install lzma : SKIP
build xapian-core :
  configure xapian-core : SKIP
  compile xapian-core : SKIP
  install xapian-core : SKIP
build icu4c :
  configure icu4c : SKIP
  compile icu4c : SKIP
  install icu4c : SKIP
build libzim :
  configure libzim : SKIP
  compile libzim : OK
  test libzim : OK
  install libzim : OK
build libaria2 :
  configure libaria2 : SKIP
  compile libaria2 : SKIP
  install libaria2 : SKIP
build kiwix-lib :
  configure kiwix-lib : SKIP
  compile kiwix-lib : OK
  test kiwix-lib : OK
  install kiwix-lib : OK
build kiwix-android :
  configure kiwix-android : ERROR
Traceback (most recent call last):
  File "/usr/local/bin/kiwix-build", line 9, in <module>
    load_entry_point('kiwix-build==0.1', 'console_scripts', 'kiwix-build')()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/__init__.py", line 674, in main
    builder.run()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/__init__.py", line 609, in run
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/__init__.py", line 593, in build
    builder.build()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependencies.py", line 448, in build
    super().build()
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependency_utils.py", line 414, in build
    self.command('configure', self._configure)
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependency_utils.py", line 232, in command
    return self.target.command(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependency_utils.py", line 54, in command
    ret = function(*args, context=context)
  File "/usr/local/lib/python3.5/dist-packages/kiwixbuild/dependencies.py", line 458, in _configure
    pj(self.build_path, 'kiwixlib', 'src', 'main'))
  File "/usr/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mhutti1/kiwix-build/BUILD_native_dyn/INSTALL/kiwix-lib'

**Comment by mhutti1** [comment]
It might be that I am still running the old kiwix-build though. I have done pip install . but I am not experienced in python dependency management.

**Comment by automactic** [comment]
It works! Tested on macOS 10.13.5, meson 0.43.0, ninja 1.8.2.

**Comment by mgautierfr** [comment]
@mhutti1 Are you sure you have this commit https://github.com/kiwix/kiwix-build/pull/175/commits/5b92e1d2e4343927dbcf923d930775bfc06e51da ?

You may need to use the --upgrade option (`pip install --upgrade .`)

**Comment by mhutti1** [comment]
I have got the multi-arch apk building now but single arch apks break with ```kiwix-build kiwix-android --target-platform android_arm``` gives:

```[INSTALL PACKAGES]
 - automake : SKIP
 - libtool : SKIP
 - cmake : SKIP
 - git : SKIP
 - subversion : SKIP
 - ccache : SKIP
 - pkg-config : SKIP
 - gcc : SKIP
 - autopoint : SKIP
 - libbz2-dev : SKIP
 - libmagic-dev : SKIP
 - default-jdk : SKIP
SKIP, No package to install.
[SETUP PLATFORMS]
[PREPARE]
prepare sources android-ndk :
  download android-ndk : SKIP
  extract android-ndk : SKIP
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources uuid :
  download uuid : SKIP
  extract uuid : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c : SKIP
  svnupdate icu4c : SKIP
  patch icu4c : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : SKIP
prepare sources kiwix-lib :
  gitclone kiwix-lib : SKIP
  gitupdate kiwix-lib : OK
prepare sources kiwix-android :
  gitclone kiwix-android : SKIP
  gitupdate kiwix-android : OK
[BUILD]
build android-ndk (android_arm):
  build_platform android-ndk : OK
  fix_permission_right android-ndk : OK
build pugixml (android_arm):
  configure pugixml : OK
  compile pugixml : OK
  test pugixml : SKIP
  install pugixml : OK
build zlib (android_arm):
  pre_build_script zlib : OK
  configure zlib : OK
  compile zlib : OK
  install zlib : OK
build lzma (android_arm):
  configure lzma : OK
  compile lzma : OK
  install lzma : OK
build uuid (android_arm):
  configure uuid : OK
  compile uuid : OK
  install uuid : OK
build xapian-core (android_arm):
  configure xapian-core : OK
  compile xapian-core : OK
  install xapian-core : OK
build icu4c (native_static):
  configure icu4c : OK
  compile icu4c : OK
  install icu4c : OK
build icu4c (android_arm):
  configure icu4c : OK
  compile icu4c : OK
  install icu4c : OK
build libzim (android_arm):
  configure libzim : OK
  compile libzim : OK
  test libzim : SKIP
  install libzim : OK
build libaria2 (android_arm):
  configure libaria2 : OK
  compile libaria2 : OK
  install libaria2 : OK
build kiwix-lib (android_arm):
  configure kiwix-lib : OK
  compile kiwix-lib : OK
  test kiwix-lib : SKIP
  install kiwix-lib : OK
build kiwix-android (android_arm):
  configure kiwix-android : OK
  compile kiwix-android : ERROR
Starting Build
Settings evaluated using settings file '/home/mhutti1/kiwix-build/BUILD_android_arm/kiwix-android/settings.gradle'.
Projects loaded. Root project using build file '/home/mhutti1/kiwix-build/BUILD_android_arm/kiwix-android/build.gradle'.
Included projects: [root project 'kiwix-android', project ':app', project ':kiwixlib']
Evaluating root project 'kiwix-android' using build file '/home/mhutti1/kiwix-build/BUILD_android_arm/kiwix-android/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/mhutti1/kiwix-build/BUILD_android_arm/kiwix-android/build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'kiwix-android'.
> Could not find method google() for arguments [] on repository container.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

**Comment by mgautierfr** [comment]
For single arch you still need to use the `android` platform but use `--android-arch` option to limit to one arch only :
`kiwix-build kiwix-android --android-arch arm`
(See the new README : https://github.com/kiwix/kiwix-build/pull/175/files#diff-04c6e90faac2675aa89e2176d2eec7d8R129)

**Pull request merged**
