### PR TITLE
Use standard name for CI

### PR DESCRIPTION
**Pull request by kelson42**

### CODE REVIEW

**Comment by mgautierfr** [comment]
This is named "Build base" because this workflow build the bases (dependencies) for other projects.
We may (and will) have other workflow in the futur ("Build release", "PullRequest", ...)

**Comment by kelson42** [comment]
@mgautierfr Currently what is called "Build base" in `.github/workflows/` is what is run on each PR? If not, in which file is that defined?

**Comment by mgautierfr** [comment]
Yes. Ideally we should have a different workflow for the pr and the schedule build. But for now we have only one.

**Comment by kelson42** [comment]
@mgautierfr AFAIK all of this is the CI (more or less directly, we just have workflows to optimize things) and we need a Workflow called "CI" like in any other repo. in our organization. I have been working to standardize the way how we do CI and how we report and I want to get it through.

**Pull request merged**
