### PR TITLE
Build libzim on bionic

### LINKED ISSUE #595: Build Linux libzim on Bionic
I know you just switched from Bionic to focal; with good reasons I believe but it has some unfortunate consequence for python-libzim distribution.

Binary python packages that are not pure python are tied to a `platform` that helps package managers (`pip`) pick the appropriate file for an installation.

This notion of _platform_ is somewhat flexible. In Linux, it defaults to `linux` but can be set more specifically to announce (and should respect) libc-compatibility. There are thus `manylinux_1`, `manylinux_2010`, `manylinux_2014`, and now it's clearer with `manylinux_2_28` and the likes.

> PEP600 states that a wheel tagged manylinux_x_y shall work on any distro based on glibc>=x.y

It's recommended to use them of course as the package manager can detect an incompatible platform while using `linux`, your user could install a non-compat one and crash at runtime.

For pylibzim, we've been incorrectly setting the platform as `manylinux1` (glic 2.5) while we were building on Focal (glibc 2.31). That's bad 🫣

Now that we have a better building process, we'd like to fix that as well but it's not possible:
- libzim is built on focal (glibc 2.31)
- [manylinux project](https://github.com/pypa/manylinux) doesn't provide an [image](https://quay.io/organization/pypa) for building on 2.31. Latest they propose if 2.28

This leaves us with the following choice:
- **A**. Build for `linux`.
  - Mostly work as our users are on 2.31+
  - Prevents us from running the symbols check in the CI
  - Prevents us from automaticly testing the wheels in the CI (tests are ran in another workflow though)
- **B**. Create a manylinux-like image with 2.31+
  - It's a lot of work
- **C**. Wait for manylinux to distribute a 2.31+ image
  - No idea about when that could be.

Hence this ticket. With a bionic-built libzim, we could properly set `manylinux_2_28`.

### PR DESCRIPTION
**Pull request by mgautierfr**
Fix #595

### CODE REVIEW

**Comment by mgautierfr** [comment]
@rgaudin, is https://tmp.kiwix.org/ci/libzim_bionic/libzim_linux-x86_64-bionic-2023-04-19.tar.gz ok for you ?

**Comment by rgaudin** [comment]
@mgautierfr perfect 👍

**Comment by rgaudin** [comment]
For some reason there is no aarch64-bionic. Or the name hasn't been fixed

**Comment by kelson42** [comment]
@mgautierfr @rgaudin All good here? Ready to merge?

**Comment by rgaudin** [comment]
Testing the aarch64-bionic from yesterday now

**Comment by rgaudin** [comment]
Unfortunately, this is not working. It looks like it's due to the gcc version used in the cross-compilation toolchain (10.3.0).

```
ldd -r -v libzim_linux-aarch64-bionic-2023-04-25/lib/aarch64-linux-gnu/libzim.so.8.1.0
libzim_linux-aarch64-bionic-2023-04-25/lib/aarch64-linux-gnu/libzim.so.8.1.0: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by libzim_linux-aarch64-bionic-2023-04-25/lib/aarch64-linux-gnu/libzim.so.8.1.0)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000005502b19000)
	librt.so.1 => /lib64/librt.so.1 (0x0000005502b4e000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x0000005502b6f000)
	libm.so.6 => /lib64/libm.so.6 (0x0000005502d13000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000005502dd4000)
	libc.so.6 => /lib64/libc.so.6 (0x0000005502e05000)
	/lib/ld-linux-aarch64.so.1 (0x0000005500000000)
undefined symbol: _ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1Ev, version GLIBCXX_3.4.26	(libzim_linux-aarch64-bionic-2023-04-25/lib/aarch64-linux-gnu/libzim.so.8.1.0)
undefined symbol: _ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1Ev, version GLIBCXX_3.4.26	(libzim_linux-aarch64-bionic-2023-04-25/lib/aarch64-linux-gnu/libzim.so.8.1.0)

	Version information:
	libzim_linux-aarch64-bionic-2023-04-25/lib/aarch64-linux-gnu/libzim.so.8.1.0:
		libgcc_s.so.1 (GCC_3.0) => /lib64/libgcc_s.so.1
		librt.so.1 (GLIBC_2.17) => /lib64/librt.so.1
		libpthread.so.0 (GLIBC_2.17) => /lib64/libpthread.so.0
		libm.so.6 (GLIBC_2.17) => /lib64/libm.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
		libstdc++.so.6 (GLIBCXX_3.4.20) => /lib64/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.8) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.18) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.9) => /lib64/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.9) => /lib64/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.11) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.26) => not found
		libstdc++.so.6 (CXXABI_1.3) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.11) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.14) => /lib64/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.5) => /lib64/libstdc++.so.6
		libstdc++.so.6 (CXXABI_1.3.3) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.22) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.15) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.19) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4.21) => /lib64/libstdc++.so.6
		libstdc++.so.6 (GLIBCXX_3.4) => /lib64/libstdc++.so.6
	/lib64/libpthread.so.0:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/librt.so.1:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
		libpthread.so.0 (GLIBC_PRIVATE) => /lib64/libpthread.so.0
		libpthread.so.0 (GLIBC_2.17) => /lib64/libpthread.so.0
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libstdc++.so.6:
		libm.so.6 (GLIBC_2.17) => /lib64/libm.so.6
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		libgcc_s.so.1 (GCC_4.2.0) => /lib64/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.3) => /lib64/libgcc_s.so.1
		libgcc_s.so.1 (GCC_3.0) => /lib64/libgcc_s.so.1
		libc.so.6 (GLIBC_2.18) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libm.so.6:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		libc.so.6 (GLIBC_PRIVATE) => /lib64/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libgcc_s.so.1:
		libc.so.6 (GLIBC_2.17) => /lib64/libc.so.6
	/lib64/libc.so.6:
		ld-linux-aarch64.so.1 (GLIBC_2.17) => /lib/ld-linux-aarch64.so.1
		ld-linux-aarch64.so.1 (GLIBC_PRIVATE) => /lib/ld-linux-aarch64.so.1
```

```
# strings /usr/lib64/libstdc++.so.6.0.25 |grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_DEBUG_MESSAGE_LENGTH
GA+GLIBCXX_ASSERTIONS
```

@mgautierfr could an earlier version of gcc work?  I see [a few other options](https://sourceforge.net/projects/raspberry-pi-cross-compilers/files/Bonus%20Raspberry%20Pi%20GCC%2064-Bit%20Toolchains/Raspberry%20Pi%20GCC%2064-Bit%20Cross-Compiler%20Toolchains/Stretch/) but I don't know what kiwix-build needs and looking at [this table](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html) it seems like we'd need to go back as far as GCC 8.1.0 to match `GLIBCXX_3.4.25`.

That would require us to use `6.3.0`. Is that usable/realistic?

**Comment by mgautierfr** [comment]
@rgaudin can you try the new aarch64-bionic ?

**Comment by rgaudin** [comment]
> @rgaudin can you try the new aarch64-bionic ?

Works fine 👍

**Comment by kelson42** [comment]
@rgaudin So you approve and we can merge?

**Review by rgaudin — APPROVED** [review]
👍

**Comment by rgaudin** [comment]
The Draft to non-draft didn't trigger a notification 🤷‍♂️

**Pull request merged**
