### PR TITLE
Add target aarch64_musl_*

### PR DESCRIPTION
**Pull request by mgautierfr**
I have to mention that adding a new cross compiled target never seems so simple.

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr It seems we have a few problems on 4 systems

**Comment by kelson42** [comment]
@mgautierfr Only one failing ompilations left, but fail scenario seems not that straight

**Comment by kelson42** [comment]
@mgautierfr Does it fixes any ticket? #585 for example? The rule is no PR without ticket because this avoids this kind of unclarity.

**Comment by mgautierfr** [comment]
#585 is not fixed yet. Linux x86_64_musl is not done.

**Pull request merged**
