### PR TITLE
[WIP] Try to build on Windows Github-actions.

### PR DESCRIPTION
**Pull request by mgautierfr**

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Is the goal here to impelement #466 ?

**Comment by kelson42** [comment]
@mgautierfr What is the status of this PR?

**Comment by mgautierfr** [comment]
This is a draft PR to try to build on github action on Windows.
I'm still working on it. We should keep it.

**Comment by kelson42** [comment]
@mgautierfr This PR needs an update, what is the superseeding PR?

**Comment by mgautierfr** [comment]
Superseded by https://github.com/kiwix/kiwix-build/pull/703, https://github.com/kiwix/kiwix-build/pull/715, https://github.com/kiwix/kiwix-build/pull/725 (among others)

**Pull request closed without merging**
