### PR TITLE
Remove kiwix-desktop console for release versions

### PR DESCRIPTION
**Pull request by jetownfeve21**
fix https://github.com/kiwix/kiwix-desktop/issues/373

### CODE REVIEW

**Comment by jetownfeve21** [comment]
@mgautierfr Based on https://www.appveyor.com/docs/branches/#build-on-tags-github-bitbucket-gitlab-gitea I wonder if the APPVEYOR_REPO_TAG variable is about the kiwix-build repo or the kiwix-desktop repo ?

**Comment by jetownfeve21** [comment]
@mgautierfr I use the `APPVEYOR_SCHEDULED_BUILD` environment variable which is set to true if the build runs by scheduler but it's also true when appveyor is launched by a push, so I don't know if it will work correctly for the release

**Comment by kelson42** [comment]
@mgautierfr Can you please answer @jetownfeve21 ?

**Comment by mgautierfr** [comment]
Seems good.

**Pull request merged**
