### PR TITLE
Move all our CI/CD to focal instead of bionic

### LINKED ISSUE #587: Move from Ubuntu 18.04 to Ubuntu 20.04 as mnimum version supported
Ubuntu 18.04 is EOL and this is necessary anyway to fix/implement a few tickets.

### PR DESCRIPTION
**Pull request by mgautierfr**
Bionic is EOL.

Fix #587

### CODE REVIEW

**Comment by kelson42** [comment]
@mgautierfr Don't forget to update the readme

**Comment by mgautierfr** [comment]
There is nothing on the readme related to that. Or I miss something ?

**Comment by kelson42** [comment]
First line of the README. AFAIK we know secure that our build works on Ubunuti 20.04, not 18.04 anymore.

**Comment by mgautierfr** [comment]
Good catch. I've missed it as it is split in several line (and link in the middle).

> Otherwise, are we good to merge?

Yes

**Pull request merged**
