### PR TITLE
Git update now updates to latest commit

### PR DESCRIPTION
**Pull request by mhutti1**
When testing I discovered that kiwix-android is not updated on each run.

### CODE REVIEW

**Comment by mgautierfr** [comment]
> When testing I discovered that kiwix-android is not updated on each run.

Ho, you're right. That is bad and must be fixed.

However :
- In a general way, I really want that kiwix-build do not overwrite any changes made by a user in the source directory. This way a user (me 😄) can patch a source and run kiwix-build to test without lost its work.
- I dislike a lot `git pull`. The default behavior of `git pull` is to fetch the last version from remote (and we are already doing `git fetch`) and **merge** the origin branch into the local one. Most of the time, if you have local change commited (but not pushed), you will want to do a `rebase` and not a `merge`.

I would prefer something that check that no modification is made on the source tree (working tree clean, and no "new" branch currently checkout) and SKIP if it the case. And if every thing is right, launch a `git merge --ff-only`

**Comment by kelson42** [comment]
@mhutti1 Anything blocking for you to go ahead on that branch?

**Comment by mhutti1** [comment]
Haven't got round to it yet.

**Comment by mhutti1** [comment]
@mgautierfr How about using https://stackoverflow.com/questions/3216360/merge-update-and-pull-git-branches-without-using-checkouts with the --update-head-ok flag?

**Comment by kelson42** [comment]
Could we go ahead on that PR?

**Comment by mgautierfr** [comment]
Superseded by #413

**Pull request closed without merging**
