### PR TITLE
[CUSTOM_APP] Add a zim_path option to build_custom_app.py

### PR DESCRIPTION
**Pull request by mgautierfr**
If the user what to make a custom_app locally, he will need to download
the zim file before. As he has already the zim, it is better to give
the zim_path instead of give the zim_url and have `build_custom_app.py`
download a second time the zim.

### CODE REVIEW

**Comment by kelson42** [comment]
All this is extremely confusing.

**Comment by kelson42** [comment]
Here is how it should work:
1 - custom app are build from json files, so customize your file if you want
2 - if you really want to give parameter on the command line, a generic option should be provided to overwritte any json field
3 - zim_path/zim_url is the same, remove one of them (like it was before) and download if this is a http link (with continue option)

**Comment by mgautierfr** [comment]
The script is intended to be run on travis. All options being automatically set by using the json file in the kiwix/kiwix-android-custom repository.

This option is needed as the build using travis is broken because of #59 and we use this option only as workaround.

If this seems too confusing, I can hide the option itself. (this is already the case for a lot of options used in the command described [here](https://github.com/kiwix/kiwix-build/wiki/Build-and-publish-a-custom-app-locally-(without-travis)#upload-apks) )

> zim_path/zim_url is the same, remove one of them (like it was before) and download if this is a http link (with continue option). Otherwise it's really unclear which has the priority etc...

A path is not the same thing that a url. The information in zim_url in the json file will be used by script running in travis. Having a local path will not work.

**Comment by mgautierfr** [comment]
I'm closing this PR as #66 supersedes this one and it should not be merged.

However, fell free to continue the discussion here or on #66.

**Pull request closed without merging**
