### PR TITLE
Switch (again) to new arm cross-compilation toolchain.

### PR DESCRIPTION
**Pull request by mgautierfr**
This introduce a difference between armv6 and armv8.

### CODE REVIEW

**Comment by rgaudin** [comment]
Tested the three versions on a Pi400 ; all of them work as expected.

```
kiwix-tools_linux-aarch64-2023-05-16/kiwix-serve: ELF 64-bit LSB executable, ARM aarch64, version 1 (GNU/Linux), statically linked, for GNU/Linux 4.19.255, with debug_info, not stripped
kiwix-tools_linux-armv6-2023-05-16/kiwix-serve:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 4.19.255, with debug_info, not stripped
kiwix-tools_linux-armv8-2023-05-16/kiwix-serve:   ELF 32-bit LSB executable, ARM, EABI5 version 1 (GNU/Linux), statically linked, for GNU/Linux 4.19.255, with debug_info, not stripped
```

**Comment by kelson42** [comment]
@mgautierfr I have just rebased, not sure which ticket it fixes?! But what stops us to merge?

**Comment by mgautierfr** [comment]
Fixes https://github.com/kiwix/kiwix-build/issues/613

I would prefer have a confirmation from @holta that it works for him.

**Comment by rgaudin** [comment]
@mgautierfr I just tested with a Pi0W and it works fine (armv6 version of course)

```sh
reg@raspberrypi:~ $ uname -a
Linux raspberrypi 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
reg@raspberrypi:~ $ ./kiwix-serve --version
kiwix-tools 3.5.0

libkiwix 12.0.0
+ libzim 8.2.0
+ libxapian 1.4.22
+ libcurl 7.67.0
+ libmicrohttpd 0.9.76
+ libz 1.2.12
+ libicu 58.2.0
+ libpugixml 0.12.0

libzim 8.2.0
+ libzstd 1.5.2
+ liblzma 5.2.6
+ libxapian 1.4.22
+ libicu 58.2.0
```
Screenshot 2023-05-22 at 12 09 35

Good to merge for me.

**Review by rgaudin — APPROVED** [review]

**Comment by holta** [comment]
> @mgautierfr I just tested with a Pi0W and it works fine (armv6 version of course)

Reconfirmed.

Many thanks @mgautierfr for all your hard work.

**Pull request merged**
