### PR TITLE
Added CI image for Alpine

### PR DESCRIPTION
**Pull request by veloman-yunkan**
Related to openzim/libzim#709

The PR only enhances the Docker job so that it creates Alpine images that can be used in the openzim/libzim CI. Alpine is not added to the list of configurations used in the kiwix-build CI workflows.

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
I started working on this PR on an outdated version of my clone of the `kiwix-build` repository. As a result of that mistake the docker image [kiwix/kiwix-build_ci:alpine-31](https://hub.docker.com/layers/kiwix-build_ci/kiwix/kiwix-build_ci/alpine-31/images/sha256-aa7e7e3107ea24fb84aadd00e464c95c49716be75adfaa41cb424fc44b0670dc?context=explore) was published by the first CI run. It must be removed. The correct image is `kiwix/kiwix-build_ci:alpine-32`.

**Comment by veloman-yunkan** [comment]
@mgautierfr It took several attempts and a couple of hacks to make it work. I preserved entire history so that you can make sure that I didn't mess up with DockerHub in the process.

**Comment by kelson42** [comment]
@mgautierfr Any review in sight?

**Comment by mgautierfr** [comment]
Agree with the final code.
@veloman-yunkan please rebase-fixup before we merge.

**Comment by veloman-yunkan** [comment]
@mgautierfr Done

**Review by mgautierfr — APPROVED** [review]

**Pull request merged**
