### PR TITLE
New libkiwix build due to bundled libcurl dep issue

### PR DESCRIPTION
**Pull request by rgaudin**

### CODE REVIEW

**Comment by veloman-yunkan** [comment]
I am now investigating a problem with building `libcurl` under Windows in release mode. I wanted to find out why that problem is not present in our CI. While looking for information in our CI history, issues and PRs, I came across this PR. Sadly, there is absolutely nothing in this PR that helps to understand what the issue was:
- There is no clue either in the title or in the change itself
- Description is missing
- No issue/ticket is linked to this PR
I believe that proper trace is an important part of any change. Though it may be rarely needed, when it's not there at the time of need it may be too difficult to recover.

**Comment by veloman-yunkan** [comment]
BTW, it turns out that the Windows build of `libkiwix` was not created by the CI run caused by this PR. See https://github.com/kiwix/kiwix-build/actions/runs/11405853054/job/31738250419 and https://tmp.kiwix.org/ci/dev_preview/libkiwix-14.0.0-1/. Also there is no Windows build of `libkiwix` in https://tmp.kiwix.org/ci/dev_preview/libkiwix_14.0.0/ either.

**Comment by rgaudin** [comment]
@veloman-yunkan sorry about that. I just updated the PR but this is a build-request PR so probably not the best place to look for.

Please take a look at https://github.com/kiwix/kiwix-build/pull/765 where the actual fix hapened.

The process of getting a new build of the dependencies is broken to my opinion in that it required the workflows to run fist, have a bunch of them fail and then re-run them (using the retry failed ones Github button) to eventually have the CI pass.
It was exactly the same scenario for that previous PR AFAICT (libmicrohttpd).

Let me know if there is any information missing

**Comment by veloman-yunkan** [comment]
@rgaudin Thanks!

**Pull request merged**
