### PR TITLE
Execute nightly at 3AM (in place of 1AM)

### LINKED ISSUE #770: Bad archive base_deps_windows_native_static_09.tar.gz
The archive at https://tmp.kiwix.org/ci/base_deps_windows_native_static_09.tar.gz seems to be corrupted.

```
$ tar tzf base_deps_windows_native_static_09.tar.gz 
SOURCE/icu4c-73.2/.extract_ok
SOURCE/pugixml-1.2/.extract_ok
...
... /* omitting some output */
....
BUILD_win-amd64/INSTALL/bin/icuuc74.dll
BUILD_win-amd64/INSTALL/bin/testplug.dll
BUILD_win-amd64/libcurl/.install_ok

gzip: stdin: decompression OK, trailing garbage ignored
BUILD_win-amd64/xapian-core-1.4.26/.test_ok
BUILD_win-amd64/zlib-1.2.12/.compile_ok
BUILD_win-amd64/docoptcpp-0.6.2/.install_ok
ARCHIVE/.download_boostregex_ok
ARCHIVE/.download_libcurl_ok
ARCHIVE/.download_docoptcpp-0.6.2_ok
tar: Child returned status 2
tar: Error is not recoverable: exiting now
```

There is no such problem with its [predecessor](https://tmp.kiwix.org/ci/base_deps_windows_native_static_08.tar.gz).

### PR DESCRIPTION
**Pull request by kelson42**
Fixes #770

Executing the nightly 2 hours after the CI

### CODE REVIEW

**Comment by kelson42** [comment]
@veloman-yunkan Do we have again/still a malformed archive? The CI does not pass!

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan Do we have again/still a malformed archive? The CI does not pass!

The [corrupted archive](https://github.com/kiwix/kiwix-build/issues/770#issuecomment-2441801068) has to be removed again before we can hope for a clean CI.

**Comment by kelson42** [comment]
@rgaudin Could you please do that again please?

**Comment by kelson42** [comment]
@veloman-yunkan I have removed the corrupted file and now CI is green. Good to merge?

**Review by veloman-yunkan — APPROVED** [review]
The file at https://tmp.kiwix.org/ci/base_deps_windows_native_static_09.tar.gz is good now.

**Pull request merged**
