### PR TITLE
Language data is packaged into ICU

### PR DESCRIPTION
**Pull request by veloman-yunkan**
With language data not put into the ICU package, `icu::Locale::getDisplayLanguage()` doesn't work correctly. This is required by kiwix/libkiwix#553 (see https://github.com/kiwix/libkiwix/pull/553/commits/0198cdafaeddc6fe12a9875f4525effb998f4671).

### CODE REVIEW

**Comment by kelson42** [comment]
We have to be careful here. At least for the Android JNI binding there was a time where this data file was loaded dynamically. The idea was to reduce the size of the universal APK. Not sure this is stillt he case though.

**Comment by mgautierfr** [comment]
You also have to bump the base_deps_meta_version https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/versions.py#L42 to trigger a rebuild of the dependencies in the CI.

---

This ICU data is something we have to think about and fix "once and for all".

We are splitting this data out of ICU only for android (as we don't want to duplicate the data in several arch dependent library).
The data is packaged by kiwix-android application itself (and stored in in the git repository https://github.com/kiwix/kiwix-android/tree/develop/app/src/main/assets/icu).
It should be to libkiwix to package it (in the generated `.aar`) or better to https://github.com/kiwix/java-libkiwix to do it.

For reference :

https://github.com/kiwix/kiwix-build/pull/44 (which doesn't help a lot as the discussion has been held in private)
https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/dependencies/libkiwix.py#L77-L79
https://github.com/kiwix/kiwix-android/blob/ec823be2942a770723ad3100dc3c38c4782c2cf6/app/src/main/java/org/kiwix/kiwixmobile/ZimContentProvider.java#L267-L295

**Review by mgautierfr — CHANGES_REQUESTED** [review]
We need to change base_deps_meta_version to trigger a rebuild of the dependencies.

**Comment by kelson42** [comment]
@mgautierfr This needs to be reviewed, merged in prio because of blocking other PRs in libkiwix.

**Comment by kelson42** [comment]
@veloman-yunkan I have rebased on latest master,  unfortunatley the CI does not pass, at least for macOS.

**Comment by veloman-yunkan** [comment]
> @veloman-yunkan I have rebased on latest master, unfortunatley the CI does not pass, at least for macOS.

@kelson42 From the [**CI/Macos (native_dyn)** build log](https://github.com/kiwix/kiwix-build/pull/494/checks?check_run_id=3064264139):

```
+ aclocal -I m4
./autogen.sh: line 30: aclocal: command not found
```

This error hardly has any connection with my changes.

**Review by mgautierfr — APPROVED** [review]

**Comment by mgautierfr** [comment]
I've rebase-fixup on master. And fix aclocal on macos. We can merge once CI pass.

**Comment by mgautierfr** [comment]
The falling test is not related to this PR (https://github.com/kiwix/libkiwix/issues/592)
We can merge right now.

**Pull request merged**
