### PR TITLE
Fix ios

### PR DESCRIPTION
**Pull request by mgautierfr**

### CODE REVIEW

**Comment by automactic** [comment]
It works.

But please note user have to use `install_path_tool` to modify install paths in the dylib so iOS knows where to find the file. I have a script for this.

**Comment by mgautierfr** [comment]
Can you try with meson 0.43.0 and with the `-fembed-bitcode` (https://github.com/kiwix/kiwix-build/pull/166/commits/056de4343f3caec4e5c6cd285eb7066a74a78193) ?

**Comment by automactic** [comment]
I changed it back to static build and reenabled `-fembed-bitcode`, using meson 0.43.0. It builds successfully.

**Comment by kelson42** [comment]
@mgautierfr Could we ahead with merging this?

**Comment by mgautierfr** [comment]
The last commit of @automactic discard my two first (and only) commits. So this PR seems useless to me.

The only real change is https://github.com/kiwix/kiwix-build/pull/166/commits/9ed0becd8b5e4cee0aed763504a14193ee02df03 and it seems not related to https://github.com/kiwix/kiwix-build/issues/165. We is still a valid change, but not in this PR.

**Comment by mgautierfr** [comment]
I've updated the PR to only keep the commit changing armv7s->armv7.
Merging.

**Pull request merged**
